apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-services-deployment
  namespace: device-sphere-services # Added namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-services
  template:
    metadata:
      labels:
        app: device-services
    spec:
      containers:
        - name: device-services
          image: rayon11/device-sphere-services:device-services_0.2
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: device-services-service
  namespace: device-sphere-services # Added namespace
spec:
  selector:
    app: device-services
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP # Change to NodePort or LoadBalancer for external access