server:
  port: 3000
  viewEngine: html

logger:
  level: debug
  filepath: ./deviceservice.log

database:
  host: localhost
  port: 5432
  user: user_device_sphere
  password: p@ssw0rd@deviceSphere
  dbname: data_device_sphere
