server:
  port: 3000
  viewEngine: html

logger:
  level: debug
  filepath: ./deviceservice.log

database:
  # host: postgres
  host: "13.200.253.161"
  # host: postgres-service.device-sphere-infra.svc.cluster.local
  port: 5432
  user: user_device_sphere
  password: p@ssw0rd@deviceSphere
  dbname: data_device_sphere
