version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user_device_sphere
      - POSTGRES_PASSWORD=p@ssw0rd@deviceSphere
      - POSTGRES_DB=data_device_sphere
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: