apiVersion: apps/v1
kind: Deployment
metadata:
  name: rule-services-deployment
  namespace: device-sphere-services # Added namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rule-services
  template:
    metadata:
      labels:
        app: rule-services
    spec:
      containers:
        - name: rule-services
          image: rayon11/device-sphere-services:rule-services_0.1
          ports:
            - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: rule-services-service
  namespace: device-sphere-services # Added namespace
spec:
  selector:
    app: rule-services
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: NodePort # Change to NodePort or LoadBalancer for external access