server:
  port: 3001
  viewEngine: html

logger:
  level: debug
  filepath: ./deviceservice.log

database:
  host: 192.168.1.6
  # host: localhost
  # host: postgres-service.device-sphere-infra.svc.cluster.local
  port: 5432
  user: user_device_sphere
  password: p@ssw0rd@deviceSphere
  dbname: data_device_sphere
